# Generated by Django 5.2.7 on 2025-10-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=250)),
                ('dueTime', models.DateField()),
                ('priority', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
